"""Deterministic AI provider used for tests and local dry runs."""

from __future__ import annotations

from collections.abc import Callable
from datetime import UTC, datetime

from plex_music_enhancer.ai.base import AIProvider
from plex_music_enhancer.ai.models import (
    AICapabilities,
    AIProviderMetadata,
    GeneratedSummary,
)
from plex_music_enhancer.prompts.renderer import RenderedPrompt

DUMMY_SUMMARY_TEXT = (
    "This is a deterministic test summary generated by the DummyProvider for testing purposes."
)


class DummyProvider(AIProvider):
    """Provider that returns deterministic test summaries without networking."""

    name = "dummy"
    model = "dummy-v1"
    prompt_version = "1.0"

    def __init__(self, *, clock: Callable[[], datetime] | None = None) -> None:
        """Create a dummy provider."""
        self._clock = clock or (lambda: datetime.now(tz=UTC))

    def validate_configuration(self) -> None:
        """Validate dummy provider configuration."""

    def capabilities(self) -> AICapabilities:
        """Return dummy provider capabilities."""
        return AICapabilities(
            provider=self.name,
            album_summary=True,
            artist_summary=True,
            network_required=False,
        )

    def provider_metadata(self) -> AIProviderMetadata:
        """Return dummy provider metadata."""
        return AIProviderMetadata(
            provider=self.name,
            model=self.model,
            configured=True,
            capabilities=self.capabilities(),
            details={"deterministic": True},
        )

    def generate_album_summary(self, prompt: RenderedPrompt) -> GeneratedSummary:
        """Generate a deterministic album summary."""
        return GeneratedSummary(
            language=prompt.variables.get("language", "en"),
            text=DUMMY_SUMMARY_TEXT,
            provider=self.name,
            model=self.model,
            prompt_name=prompt.name,
            prompt_version=prompt.version,
            created_at=self._clock(),
            confidence=1.0,
            source_count=_source_count(prompt),
            metadata={
                "artist": prompt.variables.get("artist"),
                "album": prompt.variables.get("album"),
                "prompt_length": len(prompt.rendered_text),
            },
        )

    def generate_artist_summary(self, prompt: RenderedPrompt) -> GeneratedSummary:
        """Generate a deterministic artist summary."""
        return GeneratedSummary(
            language=prompt.variables.get("language", "en"),
            text=DUMMY_SUMMARY_TEXT,
            provider=self.name,
            model=self.model,
            prompt_name=prompt.name,
            prompt_version=prompt.version,
            created_at=self._clock(),
            confidence=1.0,
            source_count=_source_count(prompt),
            metadata={
                "artist": prompt.variables.get("artist"),
                "prompt_length": len(prompt.rendered_text),
            },
        )


def _source_count(prompt: RenderedPrompt) -> int:
    """Estimate source count from populated prompt variables."""
    source_variables = {"current_summary", "wikipedia_extract", "genres", "release_date"}
    return sum(1 for variable in source_variables if prompt.variables.get(variable))
