"""Typed models for AI generation."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class GeneratedSummary(BaseModel):
    """Summary text generated by an AI provider."""

    model_config = ConfigDict(frozen=True)

    language: str
    text: str
    provider: str
    model: str
    prompt_name: str
    prompt_version: str
    created_at: datetime
    confidence: float = Field(ge=0.0, le=1.0)
    source_count: int = Field(ge=0)
    metadata: dict[str, Any] = Field(default_factory=dict)


class AICapabilities(BaseModel):
    """Capabilities exposed by an AI provider."""

    model_config = ConfigDict(frozen=True)

    provider: str
    album_summary: bool
    artist_summary: bool
    network_required: bool


class AIProviderMetadata(BaseModel):
    """Operational metadata describing a provider instance."""

    model_config = ConfigDict(frozen=True)

    provider: str
    model: str
    configured: bool
    capabilities: AICapabilities
    details: dict[str, Any] = Field(default_factory=dict)
