"""Structured AI album review generation from synchronized Plex data."""

from __future__ import annotations

from json import JSONDecodeError, loads
from os import environ
from pathlib import Path
from threading import Lock, Thread
from typing import Protocol

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from plex_music_enhancer.ai import AIManager
from plex_music_enhancer.api.models import (
    AlbumReviewContent,
    AlbumReviewGenerationResponse,
    AlbumReviewListItem,
    AlbumReviewOverviewResponse,
    StoredAlbumReview,
)
from plex_music_enhancer.cache.store import DEFAULT_CACHE_ROOT
from plex_music_enhancer.plex.sync import PlexSyncSnapshot, PlexSyncStore, SyncedAlbum, SyncedTrack
from plex_music_enhancer.prompts.renderer import RenderedPrompt
from plex_music_enhancer.utils.files import write_text_atomic

PROMPT_VERSION = "1.0"
DUMMY_PROVIDER_TEXT = (
    "This is a deterministic test summary generated by the DummyProvider for testing purposes."
)


class AlbumReviewError(Exception):
    """Raised when structured album review generation cannot continue."""


class _AIManager(Protocol):
    """Minimal AI manager API used by the review service."""

    def generate_album_summary_from_prompt(self, prompt: RenderedPrompt):
        """Generate an album review response from a rendered prompt."""


class _AlbumReviewStorePayload(BaseModel):
    """Internal persistent review store payload."""

    model_config = ConfigDict(frozen=True)

    reviews: dict[str, StoredAlbumReview] = Field(default_factory=dict)


class AlbumReviewStore:
    """Persistent JSON store for structured album reviews."""

    def __init__(self, path: Path) -> None:
        """Create a review store."""
        self.path = path

    @classmethod
    def default(cls) -> AlbumReviewStore:
        """Return the default review store inside the configured cache volume."""
        return cls(_default_reviews_path())

    def load_all(self) -> dict[str, StoredAlbumReview]:
        """Return all persisted reviews keyed by album id."""
        if not self.path.exists():
            return {}
        try:
            payload = _AlbumReviewStorePayload.model_validate_json(
                self.path.read_text(encoding="utf-8")
            )
        except (OSError, ValueError):
            return {}
        return dict(payload.reviews)

    def get(self, album_id: str) -> StoredAlbumReview | None:
        """Return a persisted review by album id."""
        return self.load_all().get(album_id)

    def save(self, review: StoredAlbumReview) -> None:
        """Persist a review without overwriting unrelated reviews."""
        reviews = self.load_all()
        reviews[review.album_id] = review
        payload = _AlbumReviewStorePayload(reviews=reviews)
        write_text_atomic(self.path, payload.model_dump_json(indent=2))


class AlbumReviewPromptBuilder:
    """Build structured AI review prompts from synchronized Plex albums."""

    def build(self, *, album: SyncedAlbum, tracks: list[SyncedTrack]) -> RenderedPrompt:
        """Return a deterministic prompt for one album."""
        track_titles = [_track_label(track) for track in sorted(tracks, key=_track_sort_key)]
        tracklist = "\n".join(f"- {title}" for title in track_titles) or "- Keine Tracks vorhanden"
        artist = album.parent_artist or "Unbekannter Interpret"
        year = str(album.year) if album.year is not None else "unbekannt"
        rendered_text = _album_review_prompt(
            artist=artist,
            album=album.title,
            year=year,
            tracklist=tracklist,
        )
        return RenderedPrompt(
            name="album_review",
            version=PROMPT_VERSION,
            rendered_text=rendered_text,
            variables={
                "artist": artist,
                "album": album.title,
                "year": year,
                "tracklist": tracklist,
                "language": "de",
            },
            template=rendered_text,
        )


class AlbumReviewService:
    """Generate and persist structured AI reviews for synchronized Plex albums."""

    def __init__(
        self,
        *,
        sync_store: PlexSyncStore | None = None,
        review_store: AlbumReviewStore | None = None,
        ai_manager: _AIManager | None = None,
        prompt_builder: AlbumReviewPromptBuilder | None = None,
    ) -> None:
        """Create the album review service."""
        self._sync_store = sync_store or PlexSyncStore.default()
        self._review_store = review_store or AlbumReviewStore.default()
        self._ai_manager = ai_manager
        self._prompt_builder = prompt_builder or AlbumReviewPromptBuilder()
        self._lock = Lock()
        self._running: set[str] = set()
        self._errors: dict[str, str] = {}

    def start_generation(self, album_id: str) -> AlbumReviewGenerationResponse:
        """Start background review generation for an album."""
        self._album_and_tracks(album_id)
        with self._lock:
            if album_id not in self._running:
                self._running.add(album_id)
                self._errors.pop(album_id, None)
                thread = Thread(
                    target=self._run_background,
                    args=(album_id,),
                    name=f"album-review-{album_id}",
                    daemon=True,
                )
                thread.start()

        return AlbumReviewGenerationResponse(status="started", album_id=album_id)

    def generate_now(self, album_id: str) -> StoredAlbumReview:
        """Generate a review synchronously for tests and internal callers."""
        album, tracks = self._album_and_tracks(album_id)
        prompt = self._prompt_builder.build(album=album, tracks=tracks)
        generated = self._configured_ai_manager().generate_album_summary_from_prompt(prompt)
        content = _structured_content(generated.text)
        review = StoredAlbumReview(
            album_id=album.rating_key,
            artist=album.parent_artist or "Unbekannter Interpret",
            album=album.title,
            year=album.year,
            tracks=[_track_label(track) for track in sorted(tracks, key=_track_sort_key)],
            content=content,
            provider=generated.provider,
            model=generated.model,
            prompt_name=generated.prompt_name,
            prompt_version=generated.prompt_version,
            created_at=generated.created_at,
        )
        self._review_store.save(review)
        with self._lock:
            self._errors.pop(album_id, None)
        return review

    def get_review(self, album_id: str) -> StoredAlbumReview:
        """Return a persisted review or raise a user-facing error."""
        review = self._review_store.get(album_id)
        if review is None:
            msg = f"No review is available for album {album_id}."
            raise AlbumReviewError(msg)
        return review

    def overview(self) -> AlbumReviewOverviewResponse:
        """Return synchronized albums with review status."""
        snapshot = self._snapshot()
        reviews = self._review_store.load_all()
        with self._lock:
            running = set(self._running)
            errors = dict(self._errors)

        items = [
            _overview_item(
                album=album,
                tracks=self._tracks_for_album(snapshot, album),
                review=reviews.get(album.rating_key),
                running=album.rating_key in running,
                error=errors.get(album.rating_key),
            )
            for album in snapshot.albums
        ]
        ratings = [
            item.rating
            for item in items
            if item.rating is not None and item.review_status == "present"
        ]
        average_rating = round(sum(ratings) / len(ratings), 1) if ratings else None
        return AlbumReviewOverviewResponse(
            albums=items,
            generated_reviews=len(ratings),
            average_rating=average_rating,
        )

    def review_count(self) -> int:
        """Return the number of persisted reviews."""
        return len(self._review_store.load_all())

    def average_rating(self) -> float | None:
        """Return the average persisted review rating."""
        ratings = [review.content.rating for review in self._review_store.load_all().values()]
        return round(sum(ratings) / len(ratings), 1) if ratings else None

    def _run_background(self, album_id: str) -> None:
        """Generate a review in the background and capture user-visible errors."""
        try:
            self.generate_now(album_id)
        except Exception as exc:  # noqa: BLE001 - background jobs must isolate failures.
            with self._lock:
                self._errors[album_id] = str(exc) or "Album review generation failed."
        finally:
            with self._lock:
                self._running.discard(album_id)

    def _album_and_tracks(self, album_id: str) -> tuple[SyncedAlbum, list[SyncedTrack]]:
        """Return the synchronized album and its tracks."""
        snapshot = self._snapshot()
        for album in snapshot.albums:
            if album.rating_key == album_id:
                return album, self._tracks_for_album(snapshot, album)

        msg = f"Album {album_id} was not found in the Plex sync snapshot."
        raise AlbumReviewError(msg)

    def _snapshot(self) -> PlexSyncSnapshot:
        """Return the persisted Plex sync snapshot."""
        snapshot = self._sync_store.load()
        if snapshot is None:
            msg = "Run Plex synchronization before generating album reviews."
            raise AlbumReviewError(msg)
        return snapshot

    def _configured_ai_manager(self) -> _AIManager:
        """Return the configured AI manager only when generation is requested."""
        if self._ai_manager is None:
            self._ai_manager = AIManager()
        return self._ai_manager

    def _tracks_for_album(
        self, snapshot: PlexSyncSnapshot, album: SyncedAlbum
    ) -> list[SyncedTrack]:
        """Return tracks belonging to an album from the sync snapshot."""
        return [
            track
            for track in snapshot.tracks
            if _same(track.parent_album, album.title)
            and _same(track.parent_artist, album.parent_artist)
            and track.library_id == album.library_id
        ]


def _album_review_prompt(*, artist: str, album: str, year: str, tracklist: str) -> str:
    """Return the structured album review prompt text."""
    return f"""Du bist ein professioneller deutschsprachiger Musikkritiker.

Artist:
{artist}

Album:
{album}

Erscheinungsjahr:
{year}

Trackliste:
{tracklist}

Ziel:
Erstelle eine fundierte Musikkritik auf Basis der gelieferten Plex-Daten.

Antworte ausschließlich als valides JSON-Objekt mit genau dieser Struktur:
{{
  "summary": "",
  "rating": 0,
  "genres": [],
  "strengths": [],
  "weaknesses": [],
  "recommendedFor": "",
  "finalVerdict": ""
}}

Regeln:
- Schreibe auf Deutsch.
- Erfinde keine Fakten, Credits, Chartplatzierungen oder historischen Aussagen.
- Nutze nur Artist, Album, Erscheinungsjahr und Trackliste aus diesem Prompt.
- rating ist eine ganze Zahl von 0 bis 100.
- Speichere keine Markdown-Formatierung und keine unstrukturierten Textblöcke.
"""


def _structured_content(text: str) -> AlbumReviewContent:
    """Parse and validate structured AI review JSON."""
    payload = _json_payload(text)
    try:
        return AlbumReviewContent.model_validate(payload)
    except ValidationError as exc:
        if text.strip() == DUMMY_PROVIDER_TEXT:
            return _dummy_content()
        msg = "AI provider returned an invalid album review schema."
        raise AlbumReviewError(msg) from exc


def _json_payload(text: str) -> object:
    """Return JSON payload from model text, tolerating fenced JSON blocks."""
    stripped = text.strip()
    if stripped.startswith("```"):
        lines = stripped.splitlines()
        if lines and lines[0].strip().startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        stripped = "\n".join(lines).strip()
    try:
        return loads(stripped)
    except JSONDecodeError as exc:
        if text.strip() == DUMMY_PROVIDER_TEXT:
            return _dummy_content().model_dump(by_alias=True)
        msg = "AI provider returned non-JSON album review content."
        raise AlbumReviewError(msg) from exc


def _dummy_content() -> AlbumReviewContent:
    """Return deterministic structured content for the DummyProvider."""
    return AlbumReviewContent(
        summary="Deterministische Testkritik des DummyProviders.",
        rating=75,
        genres=["Test"],
        strengths=["Deterministische Ausgabe"],
        weaknesses=["Keine echte Musikanalyse"],
        recommended_for="Tests und lokale Trockenläufe.",
        final_verdict="Geeignet zur Validierung der Review-Pipeline.",
    )


def _overview_item(
    *,
    album: SyncedAlbum,
    tracks: list[SyncedTrack],
    review: StoredAlbumReview | None,
    running: bool,
    error: str | None,
) -> AlbumReviewListItem:
    """Return a public overview item."""
    status = "running" if running else "present" if review else "missing"
    if error:
        status = "error"
    return AlbumReviewListItem(
        album_id=album.rating_key,
        artist=album.parent_artist or "Unbekannter Interpret",
        album=album.title,
        year=album.year,
        track_count=len(tracks),
        review_status=status,
        running=running,
        error=error,
        rating=review.content.rating if review else None,
        summary=review.content.summary if review else None,
        review=review,
    )


def _track_label(track: SyncedTrack) -> str:
    """Return a readable track label."""
    if track.index is not None:
        return f"{track.index}. {track.title}"
    return track.title


def _track_sort_key(track: SyncedTrack) -> tuple[int, str]:
    """Return deterministic track ordering."""
    return (track.index if track.index is not None else 9999, track.title.lower())


def _same(left: str | None, right: str | None) -> bool:
    """Return whether two optional Plex strings match."""
    return (left or "").casefold() == (right or "").casefold()


def _default_reviews_path() -> Path:
    """Return the persistent album reviews path inside the configured cache root."""
    raw_path = environ.get("PLEX_ENHANCER_CACHE")
    root = Path(raw_path).expanduser() if raw_path else DEFAULT_CACHE_ROOT
    return root / "reviews.json"


__all__ = [
    "AlbumReviewError",
    "AlbumReviewPromptBuilder",
    "AlbumReviewService",
    "AlbumReviewStore",
]
